apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: olab
  namespace: flux-system
spec:
  image: registry.naseyro.com/site
  interval: 1m
  secretRef:
    name: zot-flux-pull
