baseURL = 'https://naseyro.com/'
languageCode = 'en-us'
title = 'Omar Nasser'

[menu]
  [[menu.main]]
    name = 'About'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 30
