apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-site
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=ghcr.io/naseyro/olab
    argocd-image-updater.argoproj.io/site.update-strategy: digest
    argocd-image-updater.argoproj.io/site.pull-secret: pullsecret:argocd/ghcr-pull-secret
spec:
  project: default
  source:
    repoURL: 'https://github.com/naseyro/olab.git'
    targetRevision: HEAD
    path: 'manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: personal-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
